convert "Auchindoun: Auchenai Crypts.jpg"  "Auchindoun: Auchenai Crypts.png" 
convert "Auchindoun: Mana-Tombs.jpg"  "Auchindoun: Mana-Tombs.png" 
convert "Auchindoun: Sethekk Halls.jpg"  "Auchindoun: Sethekk Halls.png" 
convert "Auchindoun: Shadow Labyrinth.jpg"  "Auchindoun: Shadow Labyrinth.png" 
convert "Blackfathom_Deeps.jpg"  "Blackfathom_Deeps.png" 
convert "Blackrock Depths: Detention Block.jpg"  "Blackrock Depths: Detention Block.png" 
convert "Blackrock Depths: Upper City.jpg"  "Blackrock Depths: Upper City.png" 
convert "Black Temple.png"  "Black Temple.png" 
convert "Blackwing Lair.jpg"  "Blackwing Lair.png" 
convert "Caverns of Time: Battle for Mount Hyjal.jpg"  "Caverns of Time: Battle for Mount Hyjal.png" 
convert "Caverns of Time: Escape from Durnholde  Keep.jpg" "Caverns of Time: Escape from Durnholde  Keep.png"
convert "Caverns of Time: Opening the Dark Portal  (Black Mo.jpg" "Caverns of Time: Opening the Dark Portal  (Black Mo.png"
convert "Coilfang Reservoir: Serpentshrine  Cavern.jpg" "Coilfang Reservoir: Serpentshrine  Cavern.png"
convert "Coilfang Reservoir: The Steamvault.jpg"  "Coilfang Reservoir: The Steamvault.png" 
convert "Coilfang Reservoir: The Underbog.jpg"  "Coilfang Reservoir: The Underbog.png" 
convert "Deadmines.png"  "Deadmines.png" 
convert "Dire Maul: Capital Gardens.jpg"  "Dire Maul: Capital Gardens.png" 
convert "Dire Maul: Gordock Commons.jpg"  "Dire Maul: Gordock Commons.png" 
convert "Dire Maul: Warpwood Quarter.jpg"  "Dire Maul: Warpwood Quarter.png" 
convert "file.sh"  "file.png" 
convert "Gnomeregan.jpg"  "Gnomeregan.png" 
convert "Gruul's Lair.png"  "Gruul's Lair.png" 
convert "Hellfire Citadel: Hellfire Ramparts.jpg"  "Hellfire Citadel: Hellfire Ramparts.png" 
convert "Hellfire Citadel: Magtheridon's Lair.jpg"  "Hellfire Citadel: Magtheridon's Lair.png" 
convert "Hellfire Citadel: Shattered Halls.jpg"  "Hellfire Citadel: Shattered Halls.png" 
convert "Hellfire Citadel: The Blood Furnace.jpg"  "Hellfire Citadel: The Blood Furnace.png" 
convert "Karazhan.jpg"  "Karazhan.png" 
convert "Lower Blackrock Spire.jpg"  "Lower Blackrock Spire.png" 
convert "Magisters' Terrace.jpg"  "Magisters' Terrace.png" 
convert "Maraudon: Earth Song Falls.jpg"  "Maraudon: Earth Song Falls.png" 
convert "Maraudon: Foulspore Cavern.jpg"  "Maraudon: Foulspore Cavern.png" 
convert "Maraudon: The Wicked Grotto.jpg"  "Maraudon: The Wicked Grotto.png" 
convert "Molten Core.jpg"  "Molten Core.png" 
convert "Naxxramas.jpg"  "Naxxramas.png" 
convert "Obsidian Sanctum.png"  "Obsidian Sanctum.png" 
convert "Onyxia's Lair.jpg"  "Onyxia's Lair.png" 
convert "Razorfen Downs.jpg"  "Razorfen Downs.png" 
convert "Razorfen Kraul.jpg"  "Razorfen Kraul.png" 
convert "Ruins of Ahn'Qiraj.jpg"  "Ruins of Ahn'Qiraj.png" 
convert "Scarlet Halls.png"  "Scarlet Halls.png" 
convert "Scarlet Monastery.jpg"  "Scarlet Monastery.png" 
convert "Scholomance.jpg"  "Scholomance.png" 
convert "Shadowfang Keep.png"  "Shadowfang Keep.png" 
convert "Startholme: Service Entrance.jpg"  "Startholme: Service Entrance.png" 
convert "Stratholme: Main Gate.jpg"  "Stratholme: Main Gate.png" 
convert "Sunwell Plateau.png"  "Sunwell Plateau.png" 
convert "Tempest Keep: The Arcatraz.jpg"  "Tempest Keep: The Arcatraz.png" 
convert "Tempest Keep: The Botanica.jpg"  "Tempest Keep: The Botanica.png" 
convert "Tempest Keep: The Eye.jpg"  "Tempest Keep: The Eye.png" 
convert "Tempest Keep: The Mechanar.jpg"  "Tempest Keep: The Mechanar.png" 
convert "Temple of Ahn'Qiraj.jpg"  "Temple of Ahn'Qiraj.png" 
convert "Temple of Atal'Hakkar.jpg"  "Temple of Atal'Hakkar.png" 
convert "The Eye of Eternity.png"  "The Eye of Eternity.png" 
convert "The Stockade.jpg"  "The Stockade.png" 
convert "Uldaman.jpg"  "Uldaman.png" 
convert "Upper Blackrock Spire.jpg"  "Upper Blackrock Spire.png" 
convert "Wailing_Caverns.jpg"  "Wailing_Caverns.png" 
convert "Zul'Aman.jpg"  "Zul'Aman.png" 
convert "Zul'Farrak.jpg"  "Zul'Farrak.png" 
convert "Zul'Gurub.jpg"  "Zul'Gurub.png" 
